import { vi } from 'vitest'
import type { P2PContextType } from '@/lib/P2PContextTypes'

export function createMockP2PContext(overrides: Partial<P2PContextType> = {}): P2PContextType {
  return {
    currentUser: { id: 'u1', username: 'Alice', color: '#3498db' },
    currentRoom: { id: 'room-1', name: 'Test Room', createdAt: 1000, channels: [] },
    channels: [
      { id: 'ch-1', name: 'general', type: 'text', createdAt: 1 },
      { id: 'ch-2', name: 'random', type: 'text', createdAt: 2 },
      { id: 'vc-1', name: 'Voice', type: 'voice', createdAt: 3 },
    ],
    currentChannel: { id: 'ch-1', name: 'general', type: 'text', createdAt: 1 },
    messages: [],
    peers: [],
    activeVoiceChannel: null,
    isMuted: false,
    isDeafened: false,
    isScreenSharing: false,
    isCameraOn: false,
    localScreenShareStream: null,
    localCameraStream: null,
    localStream: null,
    remoteStreams: new Map(),
    remoteScreenStreams: new Map(),
    remoteCameraStreams: new Map(),
    watchedScreenShares: new Set(),
    isSignalingConnected: false,
    hasRoomKey: false,
    fileTransfers: new Map(),
    speakingUsers: new Set(),
    setUsername: vi.fn(),
    createRoom: vi.fn().mockResolvedValue('ROOM-CODE'),
    joinRoom: vi.fn().mockResolvedValue(undefined),
    leaveRoom: vi.fn().mockResolvedValue(undefined),
    createChannel: vi.fn().mockResolvedValue(undefined),
    selectChannel: vi.fn(),
    sendMessage: vi.fn().mockResolvedValue(undefined),
    sendGifMessage: vi.fn().mockResolvedValue(undefined),
    toggleReaction: vi.fn().mockResolvedValue(undefined),
    authorizePeerAccess: vi.fn().mockResolvedValue(undefined),
    loadOlderMessages: vi.fn().mockResolvedValue(0),
    sendFile: vi.fn().mockResolvedValue(undefined),
    registerPushForCurrentRoom: vi.fn().mockResolvedValue(undefined),
    joinVoiceChannel: vi.fn().mockResolvedValue(undefined),
    leaveVoiceChannel: vi.fn(),
    toggleMute: vi.fn(),
    toggleDeafen: vi.fn(),
    startScreenShare: vi.fn().mockResolvedValue(undefined),
    stopScreenShare: vi.fn(),
    startCamera: vi.fn().mockResolvedValue(undefined),
    stopCamera: vi.fn(),
    watchScreenShare: vi.fn(),
    stopWatchingScreenShare: vi.fn(),
    ...overrides,
  }
}
